services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    container_name: mvc_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./public/images:/var/www/html/public/images
    networks:
      - mvc_network
    depends_on:
      - mysql

  nginx:
    image: nginx:alpine
    container_name: mvc_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - mvc_network
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    platform: linux/amd64
    container_name: mvc_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-mvc_db}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_USER: ${DB_USERNAME:-mvc_user}
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mvc_network

networks:
  mvc_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
